VALID_EXTENSIONS_XLS = "xls"
VALID_EXTENSIONS_XLSX = "xlsx"
ROW_PRE = 'PRE'
ROW_MODULO = 'MODULO'
ROW_DETALLE = 'DETALLE'
ROW_PARAMETRO = 'PARAMETRO'
ROW_BAJO = "ESTANDAR BAJO"
ROW_MEDIO = "ESTANDAR MEDIO"
ROW_ALTO = "ESTANDAR ALTO"
CATEGORY_1 = "Menos de 100 m2"
CATEGORY_2 = "De 100 a 500 m2"
CATEGORY_3 = "De 500 m2 a 1000 m2"
CATEGORY_4 = "De 1000 m2 a 2500 m2"
CATEGORY_5 = "Más de 2500 m2"

BASES_CALC = {
    "TRAMITACIÓN MUNICIPAL": "m2",
    "PROYECTOS DE ESPECIALIDADES": "m2",
    "DIRECCIÓN DE OBRA": "m2",
    "PROJECT MANAGER": "weeks",
    "INSPECCIÓN TÉCNICA DE OBRA": "weeks",
    "SEGURIDAD E HIGIENE": "weeks",
    "MUDANZA Y GERENCIAMIENTO": "m2",
    "DEMOLICION": "m2",
    "BAÑOS NUEVOS": "m2/6.4",
    "BASE CONSTRUCCIÓN": "m2"
}

TYPE_B = [
    "BAÑOS NUEVOS",
    "DEMOLICION"
]

TYPE_C = [
    "TRAMITACIÓN MUNICIPAL",
    "PROYECTOS DE ESPECIALIDADES",
    "DIRECCIÓN DE OBRA",
    "PROJECT MANAGER",
    "INSPECCIÓN TÉCNICA DE OBRA",
    "SEGURIDAD E HIGIENE",
    "BASE CONSTRUCCIÓN"
]